INSTALL_SCRIPTS = {
    "nodejs": (
        'if [ -f package.json ]; then\n'
        '  echo "package.json found in root, installing npm dependencies..."\n'
        '  npm install --no-fund --no-audit 2>&1\n'
        '  if [ $? -ne 0 ]; then\n'
        '    echo "ERROR: npm install failed. Check your package.json for errors." >&2\n'
        '    exit 1\n'
        '  fi\n'
        '  echo "Dependencies installed successfully."\n'
        'else\n'
        '  echo "No package.json in root — skipping (startup command handles install)."\n'
        'fi\n'
    ),
    "python": (
        'ENTRY=""\n'
        'for f in main.py bot.py app.py server.py run.py start.py; do\n'
        '  if [ -f "$f" ]; then ENTRY="$f"; break; fi\n'
        'done\n'
        'if [ -z "$ENTRY" ]; then\n'
        '  echo "ERROR: no Python entry file found (looked for main.py, bot.py, app.py," >&2\n'
        '  echo "       server.py, run.py, start.py). Upload your bot files first." >&2\n'
        '  exit 1\n'
        'fi\n'
        'echo "Entry file: $ENTRY"\n'
        'if [ -f requirements.txt ]; then\n'
        '  echo "requirements.txt found, installing pip dependencies..."\n'
        '  pip install --no-cache-dir -r requirements.txt 2>&1\n'
        '  if [ $? -ne 0 ]; then\n'
        '    echo "ERROR: pip install failed. Check your requirements.txt for errors." >&2\n'
        '    exit 1\n'
        '  fi\n'
        '  echo "Dependencies installed successfully."\n'
        'else\n'
        '  echo "No requirements.txt found; skipping dependency install."\n'
        'fi\n'
    ),
    "ruby": (
        'if [ -f Gemfile ]; then\n'
        '  echo "Gemfile found, installing gems with bundler..."\n'
        '  gem install bundler --no-document 2>&1 && bundle install 2>&1\n'
        '  if [ $? -ne 0 ]; then\n'
        '    echo "ERROR: bundle install failed. Check your Gemfile for errors." >&2\n'
        '    exit 1\n'
        '  fi\n'
        '  echo "Dependencies installed successfully."\n'
        'else\n'
        '  echo "No Gemfile in root — skipping (startup command handles install)."\n'
        'fi\n'
    ),
    "go": (
        'if [ -f go.mod ]; then\n'
        '  echo "go.mod found, downloading modules..."\n'
        '  go mod download 2>&1\n'
        '  if [ $? -ne 0 ]; then\n'
        '    echo "ERROR: go mod download failed. Check your go.mod for errors." >&2\n'
        '    exit 1\n'
        '  fi\n'
        '  echo "Dependencies installed successfully."\n'
        'else\n'
        '  echo "No go.mod in root — skipping (startup command handles build)."\n'
        'fi\n'
    ),
    "php": (
        'if [ -f composer.json ]; then\n'
        '  if command -v composer >/dev/null 2>&1; then\n'
        '    echo "composer.json found, installing dependencies..."\n'
        '    composer install --no-interaction --no-progress 2>&1\n'
        '    if [ $? -ne 0 ]; then\n'
        '      echo "ERROR: composer install failed. Check your composer.json." >&2\n'
        '      exit 1\n'
        '    fi\n'
        '    echo "Dependencies installed successfully."\n'
        '  else\n'
        '    echo "composer.json found but composer is not available in this image;" >&2\n'
        '    echo "vendor/ dependencies will not be installed automatically." >&2\n'
        '  fi\n'
        'else\n'
        '  echo "No composer.json in root — skipping dependency install."\n'
        'fi\n'
    ),
    "bun": (
        'if [ -f package.json ]; then\n'
        '  echo "package.json found, installing dependencies with bun..."\n'
        '  bun install 2>&1\n'
        '  if [ $? -ne 0 ]; then\n'
        '    echo "ERROR: bun install failed. Check your package.json for errors." >&2\n'
        '    exit 1\n'
        '  fi\n'
        '  echo "Dependencies installed successfully."\n'
        'else\n'
        '  echo "No package.json in root — skipping (startup command handles install)."\n'
        'fi\n'
    ),
}


def install_script(runtime):
    return INSTALL_SCRIPTS.get(str(runtime or "").strip().lower(), "true")
