"""Blog / guides content — the only place article text lives.

Posts are plain data: no HTML, no templates, no Markdown parser. Each section
is a (kind, payload) tuple rendered by blog_post.html; kinds are:

  ("h2", text)                        section heading
  ("h3", text)                        sub-heading
  ("p",  text)                        paragraph
  ("ul", [item, ...])                 bullet list
  ("ol", [item, ...])                 numbered list
  ("cta", title, body, label, link)   call-to-action box; link is a
                                      ("panel", endpoint) or ("site", endpoint)
                                      pair rendered through panel_url/site_url

Keeping links out of the paragraph text means a renamed route or host can
never be stranded in an article — the template resolves every link.

Every article is about ENDHOST as a product: the app-hosting runtimes and the
deploy panel, the status engine and its embed builder, the free model. No
generic Minecraft content and no generic programming tutorials that drift off
the site's niche — the blog exists to explain the service to AdSense reviewers
and to users deciding whether to sign up.

POSTS stays in chronological order because that is how it reads and how it is
appended to; all_posts reverses it for display.
"""

POSTS = [
    {
        "slug": "what-is-minecraft-status-hosting",
        "title": "What Is Minecraft Status Hosting? The Product, Explained",
        "description": "ENDHOST runs a Discord status bot for your Minecraft server so you do not have to. Here is exactly what the service does, what it does not do, and what it costs.",
        "date": "2026-08-01",
        "date_display": "August 1, 2026",
        "category": "The service",
        "read_minutes": 4,
        "sections": [
            ("p", "A status bot is a Discord bot that checks your Minecraft server and posts the result into a channel: online or offline, current player count, slots, version and MOTD, kept up to date around the clock. ENDHOST is the thing that runs it for you. This article is the honest description of the product you will not find in a feature-list."),
            ("h2", "What the service does"),
            ("ul", [
                "It hosts the bot. You configure it in a web panel; the engine runs it 24/7. No VPS, no spare PC, no Python service to babysit.",
                "It posts one embed, not a feed. Your status channel shows a single card that the bot edits in place every minute, so the history stays clean.",
                "It checks both editions. The engine polls Java and Bedrock servers with the right protocol for each, given the address, port and edition you enter.",
                "It flips state automatically. Server down? The embed turns red and shows offline. Back up? It turns green on its own. Nobody has to touch it.",
                "It answers common questions. Optional auto-replies let the bot handle messages like 'ip' or 'how to join' without a moderator typing the same answer a hundred times.",
            ]),
            ("h2", "What the service does not do"),
            ("p", "It does not host your Minecraft server, it does not run your Discord server, and it does not store your players' data. The status side of ENDHOST is deliberately narrow: a bot per Minecraft server you own, designed to stay out of the way. Running code of your own is the other half of the platform — that is the app hosting, and it has its own articles on this blog."),
            ("h2", "What it costs"),
            ("p", "Free, permanently. There is no trial clock and no tier that unlocks features later. The running costs are covered by advertising on the public pages, which is why you will see ad slots on the marketing and panel pages. That is the entire business model — there is no premium plan hiding behind the free one."),
            ("h2", "Who it is for"),
            ("p", "Anyone who runs a Minecraft server and has a Discord where members ask 'is the server up?' — a survival server with ten friends, a network hub with a hundred player slots, a modded box that restarts overnight. If the question exists in your Discord, the service exists to answer it."),
            ("cta", "See the status embed live",
             "Create a free account, paste your server's address, and the engine posts a live status embed to your Discord channel within minutes.",
             "Create a free account", ("panel", "user_register")),
        ],
    },
    {
        "slug": "how-minecraft-status-bots-work",
        "title": "How Hosted Status Bots Work (and What the Engine Does for You)",
        "description": "Inside the hosting engine: how it checks your server, keeps one embed current, handles Java and Bedrock, and what happens when your server goes down at 3am.",
        "date": "2026-08-03",
        "date_display": "August 3, 2026",
        "category": "The service",
        "read_minutes": 5,
        "sections": [
            ("p", "Signing into the panel asks for three things — the bot token, the Discord channel, and the Minecraft address — and from then on the embed 'just works'. That simplicity is the whole engineering point of the service. This article explains what the engine is doing on each of those three inputs."),
            ("h2", "The check: one polite question to your server"),
            ("p", "Every minute the engine asks your Minecraft server its status the same way your game client does before you join. It is a lightweight network exchange, not a join: the server answers with whether it is reachable, how many players are online and what its version is. The engine then compares that answer against the last one before touching your Discord channel."),
            ("h2", "The compare: only meaningful changes hit Discord"),
            ("p", "The engine does not spam your channel with an update every sixty seconds. If nothing changed — still online, same player count — nothing is sent. If the player count changed, the embed's field numbers are edited in place. If the server stopped answering, the embed flips to the offline state you designed. Your channel sees signal, not noise."),
            ("h2", "The edit: one message, rewritten in place"),
            ("p", "Discord messages can be edited after they are sent, and that is the whole trick behind a clean status channel. The bot sends the embed once when it first starts, then edits that single message on every change. The channel does not fill with history, and members do not get notification spam from an embed that refreshes all day."),
            ("h2", "The details: editions, timeouts, retries"),
            ("p", "Java and Bedrock servers answer status checks with completely different protocols on different ports, so the engine needs to know which edition it is talking to — the panel asks for it explicitly and remembers it per bot. Timeouts are short and retries are spaced so a slow save or a restarting server does not produce a hysterical flip-flop between online and offline."),
            ("h2", "The failures: what happens at 3am"),
            ("p", "When your Minecraft server crashes or the host reboots it, the engine sees the address stop answering, flips the embed to offline within a minute or two, and leaves it there. When the server comes back with the same address, the embed flips green with the current player count. The interesting part is what does not happen: nobody has to restart the bot, because the bot is not hosted on your machine, your network, or anything you are responsible for."),
            ("cta", "Hand your status to the engine",
             "Paste your bot token and server address into the panel and the embed takes care of itself — restarts, crashes and all.",
             "Go to the panel", ("panel", "user_register")),
        ],
    },
    {
        "slug": "anatomy-of-a-discord-embed",
        "title": "The Status Embed Builder: Every Part You Design in the Panel",
        "description": "A tour of the embed builder — title, colour, fields, player-list size, and the exact wording for online and offline — and what each setting changes on your channel.",
        "date": "2026-08-06",
        "date_display": "August 6, 2026",
        "category": "The panel",
        "read_minutes": 5,
        "sections": [
            ("p", "The status embed is not a fixed design we hand you — it is built from a dozen settings in the panel's builder, with a live preview that renders as you change them. Every part of Discord's embed format maps to a setting, and knowing the map is how you make the card feel native to your community."),
            ("h2", "Title, description and footer"),
            ("p", "The title is the first line of the embed, and the builder lets you set the wording that appears when the server is online and when it is offline separately. The description carries the text under the title — usually where the server address lives. The footer holds small text and can show the last-updated time, so nobody has to ask how fresh the number is."),
            ("h2", "Fields: the data rows"),
            ("p", "Fields are the structured rows that turn the embed into a small dashboard. The builder exposes every data point the engine has — player count, maximum slots, version, MOTD — and lets you choose which are shown and in what wording. Fields can sit side by side in the same row, which is how a compact one-line status fits in a narrow channel."),
            ("h2", "Colour and player-list size"),
            ("p", "The thin colour bar on the left of the embed is a setting, not a default: pick your brand colour here. The player list is also a setting — show a scrolling list of online players, or just the count for a large server where the list would dominate the card. The wording for each state is per-state, so 'we're open' and 'we're down for a hotfix' can read like your community talks."),
            ("h2", "The live preview"),
            ("p", "Every change renders instantly in the preview beside the form, in the same Discord theme the embed will use in your channel. Nothing is saved until you save, and nothing posts to Discord until you start hosting. That round-trip — design, preview, save, start — is the entire workflow, and it is what keeps a status setup to a few minutes without touching any code."),
            ("h2", "The formatting layer"),
            ("p", "Descriptions and field values accept the formatting syntax Discord itself renders — bold text, inline code blocks, and the rest. The full list of supported patterns lives on the formatting reference page, so the design freedom has a written boundary rather than a trial-and-error one."),
            ("cta", "Design yours in the builder",
             "Open the panel, and every part of this article is a form field next to a live preview.",
             "Open the builder", ("panel", "user_register")),
        ],
    },
    {
        "slug": "free-minecraft-server-hosting",
        "title": "Free With No Catch: How a Free Status Bot Hosting Can Exist",
        "description": "The service costs money to run, but it will not cost you. How ENDHOST's ad-funded model works, what stays free, and what the privacy policy guarantees.",
        "date": "2026-08-08",
        "date_display": "August 8, 2026",
        "category": "The service",
        "read_minutes": 4,
        "sections": [
            ("p", "Hosting thousands of Discord bots costs real money — servers, bandwidth, electricity, and someone to fix them when Discord changes an API. The honest question about any free service is how it pays for itself. For ENDHOST the answer is short: advertising on the public pages, and nothing else. This article is that explanation."),
            ("h2", "Why a status bot can be free"),
            ("p", "Checking a Minecraft server and editing a Discord message is cheap work. One process can keep thousands of embeds current, which means the cost per user is tiny — small enough that advertising on the marketing and panel pages covers the whole operation. That is the entire economics of the service, and it is why there is no tier structure behind the free plan."),
            ("h2", "What free means here"),
            ("ul", [
                "No payment details are needed at signup or during use.",
                "No trial clock — nothing expires and no feature unlocks later.",
                "No queue, no shutdown timer, no world data held hostage. The service is always on; it is our job to keep it that way.",
                "No limit tied to who pays — every bot can use the builder, auto-replies and both editions.",
            ]),
            ("h2", "What advertising means for your data"),
            ("p", "The ads are the price of the free tier, but they are not the price of your account. The privacy policy is explicit: account data, email address and bot tokens are never sent to advertising partners. What ad partners see is what any browser sends when an ad loads on a public page — nothing from your panel session."),
            ("h2", "The alternative we are not doing"),
            ("p", "The other way a 'free' hosting product sustains itself is to quietly make the free tier unusable — queue-sitting, sleep timers, and export locks that make leaving expensive. That model fights its users. The ad-funded model only needs the public pages to be worth a visitor's attention, so the incentive is to make everything else genuinely good rather than artificially worse."),
            ("cta", "Take the free tier at its word",
             "Register, build an embed, and hand your status to the engine — free, and documented as such.",
             "Register free", ("panel", "user_register")),
        ],
    },
    {
        "slug": "minecraft-server-monitoring",
        "title": "What the Status Embed Tells You About Your Server's Health",
        "description": "From outside a Minecraft server you can only see what answers status checks. What the embed's online/offline signal and player count do — and honestly do not do — for monitoring.",
        "date": "2026-08-10",
        "date_display": "August 10, 2026",
        "category": "The service",
        "read_minutes": 4,
        "sections": [
            ("p", "A status embed is the most visible monitoring a Minecraft server ever gets: the whole community sees the server's state in a channel, updated every minute. But it is worth being precise about what it can and cannot tell you, so you use it as the tool it is rather than a tool it is not."),
            ("h2", "What it sees: reachability, players, version"),
            ("p", "The engine's check sees exactly what the Minecraft status protocol answers: whether the address is reachable, how many players are online, how many slots the server allows, and what version it reports. That is the same information your game client shows in the multiplayer menu — it is the ground truth for 'can players join right now', which is the question your community actually asks."),
            ("h2", "What it does not see: TPS, memory, crashes"),
            ("p", "A server can be online and running badly at the same time. The status check does not see tick rate, memory pressure, or why the process restarted. Those numbers live inside the server's own files and tools. The embed is deliberately honest about this: it reports reachability and players, and it does not pretend to know anything else."),
            ("h2", "How the two halves fit together"),
            ("p", "The practical monitoring stack for a community server is: the embed on Discord for the visible layer everyone can see, and the server's own logs and metrics for the internal layer only you can see. When the visible layer flips — the embed goes red, or the player count collapses — that is the signal to go look at the internal layer. The two halves cover each other's blind spots."),
            ("h2", "Offline flips as early warning"),
            ("p", "For a server on shared hosting that restarts overnight, the embed's offline flip is often the first notification anyone gets — faster than players complaining in general chat. The timestamp in the embed footer records exactly when the last state change happened, which turns 'the server was down' from an argument into a fact."),
            ("cta", "Put the visible layer in your Discord",
             "One embed gives your whole community the reachability signal, minute by minute, without anyone watching a dashboard.",
             "Start hosting", ("panel", "user_register")),
        ],
    },
    {
        "slug": "java-vs-bedrock-status",
        "title": "Java and Bedrock in One Panel: Getting the Check Right",
        "description": "The engine checks Java and Bedrock servers with completely different protocols. What the panel asks you for, why each field exists, and what a misconfigured check looks like.",
        "date": "2026-08-12",
        "date_display": "August 12, 2026",
        "category": "The panel",
        "read_minutes": 4,
        "sections": [
            ("p", "Java and Bedrock Minecraft servers answer status checks completely differently: different protocols, different ports, different address formats. The panel asks the questions that tell the engine which one it is talking to. Here is what each field is for and what getting it wrong looks like."),
            ("h2", "The three fields the panel asks for"),
            ("ul", [
                "Address. The public address players actually use — the one you would paste into the multiplayer menu, not 'localhost' and not a panel-internal name that only works inside your hosting provider's network.",
                "Port. Java servers default to TCP 25565, Bedrock to UDP 19132. If your server runs a custom port, this is where it goes; if it uses an SRV record, it usually does not need to be set at all.",
                "Edition. This one decides the protocol. Point a Java-style check at a Bedrock server and it will answer with bytes the checker cannot read — that is exactly why the engine refuses to guess.",
            ]),
            ("h2", "The most common misconfiguration"),
            ("p", "An address that passes the 'can I reach it' test but still shows offline almost always means one of: the port in the panel differs from the port the server actually listens on, the edition is wrong, or the address only resolves inside the provider's dashboard. The help page walks through all three cases for both editions with the exact screens to look at."),
            ("h2", "One bot per server, both on the same Discord"),
            ("p", "The panel stores the edition per bot, not per account, so one community can keep a Java bot and a Bedrock bot in two channels of the same Discord server without them stepping on each other — each embed is a separate message owned by a separate bot."),
            ("h2", "What a correct setup looks like"),
            ("p", "Green embed with the player count matching the multiplayer menu, the state flipping within a minute or two of a real crash or restart, and the version field matching the server's actual version. If you are seeing any of the failure shapes above, the panel's own help page is the shortest path to a fix — the fields are the diagnostics."),
            ("cta", "Set up the check correctly",
             "The setup guide shows the exact Developer Portal pages and field values for both editions.",
             "Read the setup guide", ("site", "help")),
        ],
    },
    {
        "slug": "auto-replies-status-bot",
        "title": "Auto-Replies: Let the Status Bot Answer Before You Do",
        "description": "The panel's auto-reply feature lets your bot answer the questions every community gets — IP, version, how to join — while the status embed handles the rest. How to set it up.",
        "date": "2026-08-15",
        "date_display": "August 15, 2026",
        "category": "The panel",
        "read_minutes": 4,
        "sections": [
            ("p", "Every Minecraft Discord has the same four questions on repeat: what is the IP, what version do you run, how do I join, and is it modded. A moderator types the same answers between gameplay sessions a dozen times a day. The panel's auto-replies exist to take over the exact answers, with your wording, before a person needs to type them."),
            ("h2", "How it works"),
            ("p", "Auto-replies are keyword triggers, not an AI chatbot: you define a word or phrase and the reply text, and the bot posts the reply in the channel where the message appeared. No machine learning, no open-ended conversation — a deliberately bounded feature that does one thing, which is stop saying the server address for the fiftieth time."),
            ("h2", "What to set up first"),
            ("ul", [
                "Address triggers — 'ip', 'address', 'join' reply with the connect string, formatted so Discord renders it cleanly.",
                "Edition triggers — 'java', 'bedrock', 'modded' answer which edition the server runs and whether mods are required.",
                "Version triggers — 'version' replies with the current release.",
                "A fallback trigger for 'status' — pointing at the status channel keeps directions in one place.",
            ]),
            ("h2", "Where the embed and the replies meet"),
            ("p", "Auto-replies answer the questions; the embed proves the answers are current. The 'is it up?' message is covered by the embed itself — the green state in the status channel is the reply. The two features split the load cleanly: the embed carries the always-true facts, the replies carry the words."),
            ("h2", "Keeping replies on-topic"),
            ("p", "Replies are per-bot, which means per-Minecraft-server: the answers are anchored to the server that bot reports on, so a community with several servers never gets the wrong IP from a well-meaning keyword match. Wording is saved as you write it, so the answers can use your community's own phrasing."),
            ("cta", "Set up your first replies",
             "The panel's replies page stores keywords and answers with per-field formatting, ready in the time it takes to type them.",
             "Open the replies page", ("panel", "user_register")),
        ],
    },
    {
        "slug": "grow-minecraft-discord-server",
        "title": "The Status Channel as a Growth Tool for Your Minecraft Discord",
        "description": "What a live status embed changes about the first five seconds of a visitor's arrival — and how the embed and auto-replies work together to make a community look alive.",
        "date": "2026-08-18",
        "date_display": "August 18, 2026",
        "category": "The service",
        "read_minutes": 4,
        "sections": [
            ("p", "A visitor's decision to stay in a Discord server is made in the first minutes, and it is made by scenery: how active the server looks before they have said a word. A live status embed is scenery that cannot be faked, because it is a live number. This article is about where that embed sits in a community that is trying to grow."),
            ("h2", "The first five seconds"),
            ("p", "Before a new member types anything, they scan the channel list. A status channel showing the server online with nine players online is a worked example of the community's claims — the number is current, the server is reachable, and the timestamp in the embed footer proves the whole thing is alive this minute. That is the difference between 'we have a community' and looking like you have a community."),
            ("h2", "The embed as an invitation"),
            ("p", "The embed's design does the inviting: the address in the description, formatted so it reads like something to paste into the game; the build-to-join field count, so a prospective player sees room to log on. A visitor who can see the server is live with open slots has already answered their own 'is it worth joining' question before they ask it."),
            ("h2", "The reply layer turns questions into answers"),
            ("p", "When the questions do come — 'ip?', 'java or bedrock?' — auto-replies answer them in the same channel, instantly, in a moderator's own wording. In moderation terms, that is the difference between a server that responds and a server that feels silent: the gap between ask and answer is one of the fastest ways to lose a first-time player."),
            ("h2", "What does not grow a server"),
            ("p", "None of this replaces the human backbone — events, staff, and an active game. What the status layer does is remove the frictions that cost growth for free: unknowable addresses, unverifiable uptime, unanswered basics, and a channel list that reads 'abandoned' at a glance. Those are the cheap wins, and they are the ones nobody else provides."),
            ("cta", "Stage your community's front room",
             "Create the embed, add the address answer to auto-replies, and the scenery starts paying for itself.",
             "Set up a status embed", ("panel", "user_register")),
        ],
    },
    {
        "slug": "deploy-your-first-app",
        "title": "Deploy Your First App: From Local Script to Always-On Container",
        "description": "ENDHOST also hosts your own code — Node.js, Python, Ruby, Go, PHP or Bun — in a container that stays up. Here is the whole deploy, field by field.",
        "date": "2026-08-20",
        "date_display": "August 20, 2026",
        "category": "App hosting",
        "read_minutes": 5,
        "sections": [
            ("p", "The status bot is one half of ENDHOST. The other half hosts code you wrote: a Discord bot, a Telegram bot, a scraper, a scheduled job, a small web service. You pick a runtime and a version, you give it a start command, and the node keeps the container running. This article walks the deploy exactly as the panel asks for it."),
            ("h2", "What counts as an app here"),
            ("p", "Anything that runs as a long-lived process in one of the six supported runtimes. If it starts on your machine with one command and keeps running until you stop it, it fits. The typical shapes are bots that hold an outbound connection to an API, workers that poll a queue, and schedulers that wake up on a timer."),
            ("h2", "The four things the deploy form asks for"),
            ("ol", [
                "A name. This is the label in your panel — it identifies the container to you, and nothing else depends on it.",
                "A runtime. Node.js, Python, Ruby, Go, PHP or Bun. The list is served by the hosting node itself, so what the form shows is what the node can actually build.",
                "A version. Each runtime offers several, and the one you pick is pinned for the life of the container. Nothing upgrades under your app.",
                "A start command. This runs inside /home/container, which is your app's working directory and the only place your files live.",
            ]),
            ("h2", "What happens when you press deploy"),
            ("p", "The panel resolves a hosting node that is answering right now, creates the container from the pinned runtime image, and starts it. The allocation summary beside the form is not decoration — the memory, CPU and disk figures shown there are the limits the container is created with, and networking is outbound: your app can reach Discord, an API or a database, and nothing on the internet dials in to it."),
            ("h2", "Adding your code"),
            ("p", "The container is created before your code is in it, which surprises people who expect a git push. From the server console you edit files and install packages in place — so a normal first deploy is: create the container, add your entry file and dependency manifest, then start it and watch the log. The default start commands install dependencies before running, so the install happens as part of the boot rather than as a separate step you have to remember."),
            ("h2", "The first thing to check"),
            ("p", "Open the live log. A container that exits immediately is almost always one of three things: the start command names a file that is not there, a dependency was never installed, or a required environment variable is missing. All three say so in the first few lines of output, and all three are a one-field fix in the panel."),
            ("cta", "Deploy something small first",
             "A ten-line script that prints a timestamp every minute proves the whole path end to end — runtime, start command, logs — before you trust it with a real bot.",
             "Create a free account", ("panel", "user_register")),
        ],
    },
    {
        "slug": "choosing-a-runtime",
        "title": "Choosing a Runtime and Pinning a Version",
        "description": "Six runtimes, several versions each, and one choice that is fixed for the life of the container. What each runtime's default start command does and how to pick a version you will not regret.",
        "date": "2026-08-22",
        "date_display": "August 22, 2026",
        "category": "App hosting",
        "read_minutes": 5,
        "sections": [
            ("p", "The runtime and version you pick at deploy time are baked into the container image. There is no in-place upgrade path — moving to a newer version means a new container — so the choice is worth thirty seconds of thought. Here is what is on offer and how the versions differ in practice."),
            ("h2", "What is live today"),
            ("ul", [
                "Node.js — 18, 20, 22 and 24, defaulting to 22. Start command: npm install && node index.js.",
                "Python — 3.10 through 3.13, defaulting to 3.13. Start command: pip install -r requirements.txt && python main.py.",
                "Ruby — 3.1 through 3.4, defaulting to 3.3. Start command: bundle install && ruby main.rb.",
                "Go — 1.21 through 1.24, defaulting to 1.23. Start command: go run .",
                "PHP — 8.1 through 8.4, defaulting to 8.3. Start command: php main.php.",
                "Bun — the 1.x line, defaulting to 1. Start command: bun install && bun run index.ts.",
            ]),
            ("h2", "Newest is not automatically right"),
            ("p", "The newest version of a runtime is the one your libraries have had the least time to catch up with. A Discord library that has not published a build for the latest release will fail at install rather than at runtime, which is a confusing first deploy. If a library's own documentation names a version it supports, pin that. If nothing objects, take the default — the defaults are the versions this platform expects most apps to run on."),
            ("h2", "The images are small on purpose"),
            ("p", "Every runtime image is Alpine-based, which keeps the container light and the start fast. The trade-off is real and worth knowing before you debug it: Alpine uses musl rather than glibc, so a dependency that ships prebuilt binaries for glibc only will try to compile from source instead. In Python that is the wheel-versus-source-build difference. If an install step takes minutes and ends in a compiler error, that is the cause — and a pure-Python or pure-JavaScript alternative to the offending package is usually the shorter path than fighting the build."),
            ("h2", "You can edit the start command"),
            ("p", "The defaults above are prefilled suggestions, not rules. If your entry point is bot.py rather than main.py, change it. If your dependencies never change, drop the install half and start faster. If you want unbuffered Python logging, python -u main.py belongs right there in the field. The command is yours; the panel just runs it in /home/container."),
            ("h2", "Changing your mind later"),
            ("p", "Because the version is pinned to the image, a version bump is a new deploy: create a container on the version you want, put the same files in it, confirm it starts, then retire the old one. That is deliberately boring — it means an upgrade can never break a running app halfway through, and you keep a working container until the new one has proved itself."),
            ("cta", "See the current runtime list",
             "The hosting page lists every runtime and version that is live right now, and the deploy form only ever shows what the node can build.",
             "See the runtimes", ("site", "hosting")),
        ],
    },
    {
        "slug": "dependency-manifests",
        "title": "Dependency Manifests: How Your Packages Actually Get Installed",
        "description": "package.json, requirements.txt, Gemfile, go.mod — what each runtime reads, why the install lives in your start command, and what that means for restarts.",
        "date": "2026-08-25",
        "date_display": "August 25, 2026",
        "category": "App hosting",
        "read_minutes": 4,
        "sections": [
            ("p", "There is no build step to configure and no dashboard where you list packages. Dependencies come from the manifest your language already uses, and the install runs as part of your start command. That design has one consequence people should know up front, so this article is mostly about that consequence."),
            ("h2", "The file each runtime reads"),
            ("ul", [
                "Node.js and Bun — package.json, installed with npm install or bun install.",
                "Python — requirements.txt, installed with pip install -r requirements.txt.",
                "Ruby — Gemfile, installed with bundle install.",
                "Go — go.mod, resolved by the go tool when it builds or runs.",
                "PHP — the default command runs your script directly, so the simplest path is a script with no third-party dependencies, or vendored code committed alongside it.",
            ]),
            ("h2", "The install is part of the boot"),
            ("p", "Look again at a default start command: npm install && node index.js. The install is not a one-time provisioning step the platform ran once — it is the first half of the command that runs whenever the container starts. Restart your app and it installs again. This is why the platform needs no build configuration at all, and it is also why a slow dependency tree shows up as a slow restart."),
            ("h2", "What that means in practice"),
            ("ol", [
                "Keep the manifest honest. Every package in it is downloaded on every start, so a dependency you stopped importing is pure restart latency.",
                "Commit a lockfile if your ecosystem has one. It makes the install deterministic, so a restart at 3am cannot pull a newer minor release that behaves differently from the one you tested.",
                "If your dependencies genuinely never change, drop the install from the start command after the first successful boot. The packages are already on the container's disk, and the app starts in a fraction of the time.",
                "If an install step is what keeps failing, run it once from the console by hand. The full output is right there, which is a much shorter feedback loop than restarting the container to read the same error again.",
            ]),
            ("h2", "Pinning versions inside the manifest"),
            ("p", "Pinning the runtime version does not pin your libraries — those are resolved fresh by the install. A bot that worked yesterday and fails today with no change from you is usually a dependency that published a new release. Version ranges in the manifest are where you control that, and narrowing them is the fix; the platform deliberately does not second-guess what your manifest asks for."),
            ("cta", "Put your manifest next to your entry file",
             "Both live in /home/container, both are editable from the panel console, and the start command ties them together.",
             "Open the panel", ("panel", "user_register")),
        ],
    },
    {
        "slug": "host-a-discord-bot-247",
        "title": "Hosting a Discord Bot 24/7 Without a VPS",
        "description": "A Discord bot on your own PC is offline whenever you are. What changes when the same code runs in a container — and what a bot needs from a host that a web app does not.",
        "date": "2026-08-27",
        "date_display": "August 27, 2026",
        "category": "App hosting",
        "read_minutes": 5,
        "sections": [
            ("p", "Every Discord bot starts on the machine its author wrote it on, and every one of them has the same problem: the bot is online exactly as long as that machine is. Closing a laptop takes the bot down. This article is about moving the same code to a container that does not close, and about the ways a bot's hosting needs differ from a website's."),
            ("h2", "A bot does not need an inbound port"),
            ("p", "This is the part that makes bot hosting simple. A gateway bot dials out to Discord and holds that connection open; Discord never connects to your bot. So there is no domain to point, no port to open, no TLS certificate to renew, and no reverse proxy to configure. Outbound networking is all a bot needs, and that is what the container has."),
            ("h2", "The deploy, for a bot specifically"),
            ("ol", [
                "Pick the runtime your library targets — Node.js for discord.js, Python for discord.py, Bun if you are already on it.",
                "Put the token in an environment variable in the panel, not in your code. Read it with process.env or os.environ, exactly as you would locally.",
                "List the library in your manifest — discord.js in package.json, discord.py in requirements.txt — so the install step picks it up.",
                "Set the start command to your entry file, and add nothing else. A bot needs no web server wrapper on this platform.",
                "Deploy, then watch the log until the library prints its ready line. That line is your proof, not the panel's status dot.",
            ]),
            ("h2", "What a crash looks like now"),
            ("p", "On your own machine, an unhandled exception kills the bot and it stays dead until you notice. In a container the process is supervised: it comes back. That is a safety net, not a fix — a bot that crashes on one malformed command will crash again on the next one, and the log is where you see the loop. The value of the restart is that a transient network blip at 4am does not cost you the whole night."),
            ("h2", "Rate limits and long tasks"),
            ("p", "Two things that hurt bots have nothing to do with hosting, and moving to a container will not solve either. A bot that hammers the API gets rate-limited by Discord regardless of where it runs, and a bot that does heavy work inside an event handler blocks its own event loop and stops answering. Both are code problems with code fixes — the host can keep your process alive, but it cannot make a blocking call return faster."),
            ("h2", "Where the status bot fits"),
            ("p", "If the bot you wanted was specifically a Minecraft status bot, you do not need to write one: that is the other product on this platform, configured in a panel with an embed builder and no code at all. The app hosting is for the bots that do not already exist as a product — your own commands, your own logic, your own token."),
            ("cta", "Move your bot off your laptop",
             "Same code, same token, same library — running in a container that stays up when you close the lid. Free, with no trial clock.",
             "Host a bot free", ("panel", "user_register")),
        ],
    },
    {
        "slug": "reading-container-logs",
        "title": "Reading the Logs: Why Your App Restarted",
        "description": "The log is the whole debugger you get on a hosted container. How to read a crash loop, the five failures that cause most of them, and how to stop your own output disappearing.",
        "date": "2026-08-29",
        "date_display": "August 29, 2026",
        "category": "The panel",
        "read_minutes": 4,
        "sections": [
            ("p", "You cannot attach a debugger to a container on someone else's node, so the log is the tool. Fortunately almost every hosting failure announces itself clearly in the first few lines of output — if the output is actually reaching the log. Both halves of that are covered here."),
            ("h2", "Making sure your output arrives"),
            ("p", "Write to standard output, not to a file. A log file inside the container is a log nobody reads: the panel streams the process's own output, and the file is invisible from outside. If your language buffers that output, a crash can take the last few lines with it — the ones that explain the crash. Python is the usual culprit, and the usual fix is python -u in the start command, or setting PYTHONUNBUFFERED to 1 as an environment variable."),
            ("h2", "The shape of a crash loop"),
            ("p", "A supervised container that fails at startup produces a distinctive pattern: the same few lines, over and over, seconds apart. Read the first cycle, not the last — the top of a cycle holds the real error, and everything after it is the same error again. If the cycles are minutes rather than seconds apart, the app was running for a while and something at runtime killed it, which is a different investigation."),
            ("h2", "The five that cause most of it"),
            ("ol", [
                "The start command names a file that is not in /home/container. The error says so by name; check the spelling and the directory.",
                "A dependency is missing from the manifest. The import error names the module — add it and restart.",
                "An environment variable is not set. A library that gets None instead of a token usually fails with something vague about authentication, so check the panel's variables before you debug the library.",
                "The token is set but wrong or revoked. Discord and most APIs answer this with an explicit unauthorised error — it is the one failure that says exactly what it is.",
                "The process finished. A script that runs top to bottom and exits is not a long-lived process; it will be started again and exit again. A bot's library normally blocks on its own, so if yours returns immediately, something in your code is not awaiting it.",
            ]),
            ("h2", "What the log will not tell you"),
            ("p", "It shows what your process printed and when it stopped, and nothing else. It does not show why the node itself restarted, and it does not show the memory graph that would explain a container killed for exceeding its allocation. If a container dies silently at a predictable point in its workload with no error at all, memory is the first suspect — the log's silence is itself the clue."),
            ("h2", "Log usefully, not loudly"),
            ("p", "One line at startup naming the version of your code, one line per meaningful state change, and full tracebacks on errors. Resist logging every loop iteration: a stream that scrolls too fast to read is functionally the same as no log at all when you actually need to find the moment something broke."),
            ("cta", "Watch the log on a real deploy",
             "Every container in the panel has a live log view — the fastest way to learn what a healthy start looks like is to read one.",
             "Open the panel", ("panel", "user_register")),
        ],
    },
    {
        "slug": "keep-tokens-out-of-code",
        "title": "Keep Your Tokens Out of Your Code",
        "description": "A bot token in a source file is one screenshot away from being someone else's. How environment variables work on this platform, how they are stored, and what to do the moment one leaks.",
        "date": "2026-09-01",
        "date_display": "September 1, 2026",
        "category": "The panel",
        "read_minutes": 4,
        "sections": [
            ("p", "The most common way a Discord bot gets stolen is not a clever attack. It is a token pasted into a source file, and then that file pasted into a help channel, a screenshot, or a public repository. The token is a password: whoever holds it is your bot, with every permission you granted it. Getting it out of your code takes two minutes and this article is those two minutes."),
            ("h2", "How the platform stores them"),
            ("p", "Tokens and environment variables are encrypted before they are written to storage, decrypted only in memory when your container needs them, and never displayed back to a browser or written to a log. That last part has a practical consequence worth stating plainly: the panel cannot show you a value you have already saved. Keep your own copy somewhere safe, or be ready to set a fresh one."),
            ("h2", "Reading a variable in your code"),
            ("ul", [
                "Node.js and Bun — process.env.DISCORD_TOKEN.",
                "Python — os.environ['DISCORD_TOKEN'], or os.environ.get for one that is genuinely optional.",
                "Ruby — ENV['DISCORD_TOKEN'].",
                "Go — os.Getenv(\"DISCORD_TOKEN\").",
                "PHP — getenv('DISCORD_TOKEN').",
            ]),
            ("h2", "Fail loudly when it is missing"),
            ("p", "Read every variable your app needs at startup and exit immediately with a clear message if one is absent. It is three lines and it converts the worst failure mode — a bot that starts, appears healthy and then behaves strangely because a value was empty — into an obvious crash with a readable log line. Use the required form of the lookup rather than the one that quietly returns nothing."),
            ("h2", "What belongs in a variable"),
            ("p", "Bot tokens, API keys, webhook URLs, database credentials, and anything else that would be a problem in someone else's hands. What does not belong there is ordinary configuration — a channel ID or a poll interval is not a secret, and putting it in code keeps it version-controlled with the logic that reads it."),
            ("h2", "If one leaks, rotate it"),
            ("p", "Do not delete the message and hope. A token that has been visible anywhere public should be assumed collected by a scraper within minutes, because that is exactly what scrapers watch for. Regenerate it at the provider, set the new value in the panel, restart the container. Nothing else you can do is a substitute for invalidating the old one, and rotating a token nobody stole costs you a restart."),
            ("cta", "Set your variables in the panel",
             "Every container has its own environment variables, encrypted at rest and injected at start — no secrets in your source files.",
             "Open the panel", ("panel", "user_register")),
        ],
    },
]


def all_posts():
    # Newest first for the listing page; POSTS itself stays chronological.
    return sorted(POSTS, key=lambda post: post["date"], reverse=True)


def get_post(slug):
    for post in POSTS:
        if post["slug"] == slug:
            return post
    return None
