import ipaddress
import re
import threading
import time
from datetime import datetime, timezone
from sys import stderr
from urllib.parse import urlsplit

import database
from crypto_util import encrypt, decrypt_strict, key_fingerprint, looks_encrypted

def _debug_print(*args, **kwargs):
    try:
        import reviews_db
        if reviews_db.is_console_debug_enabled():
            print(*args, **kwargs)
    except Exception:
        pass

_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,127}$")


NAME_MIN_CHARS = 1
NAME_INPUT_MAX_CHARS = 64
NAME_MAX_CHARS = 100
URL_MAX_CHARS = 255
# The url column may hold several comma-separated failover origins.
URL_MAX_ORIGINS = 4
TOKEN_MAX_CHARS = 512
TOKEN_ENC_MAX_CHARS = 2000
CAPACITY_MAX = 999999
NODE_LIST_MAX = 200
# A node's capacity is capped at CAPACITY_MAX, so this is not derived from it:
# it is the point past which listing every container on one node stops being
# something an operator reads and starts being a page that takes a second to
# render. Reported as truncated rather than silently cut.
SERVER_LIST_MAX = 500
NODE_ID_MAX_DIGITS = 18

_URL_SCHEMES = ("http", "https")

_LOOPBACK_HOST_NAMES = ("localhost",)

_INTEGRITY_ORA_CODES = (
    "ORA-00001",
    "ORA-01400",
    "ORA-12899",
    "ORA-02290",
    "ORA-02291",
    "ORA-02292",
)

_UNIQUE_ORA_CODE = "ORA-00001"

_NODE_PUBLIC_COLUMNS = "id, name, url, capacity, enabled, created_at"

_DEFAULT_NODE_ID = "(SELECT MIN(dn.id) FROM nodes dn)"

_SERVER_NODE_ID = "NVL(s.node_id, " + _DEFAULT_NODE_ID + ")"

_SELECT_NODES = (
    "SELECT " + _NODE_PUBLIC_COLUMNS + " FROM nodes ORDER BY id "
    "FETCH FIRST :lim ROWS ONLY"
)

_SELECT_NODES_WITH_USAGE = (
    "SELECT " + _NODE_PUBLIC_COLUMNS + ", "
    "(SELECT COUNT(*) FROM panel_servers s WHERE "
    + _SERVER_NODE_ID + "=nodes.id) AS servers "
    "FROM nodes ORDER BY id FETCH FIRST :lim ROWS ONLY"
)

_SELECT_NODE_CREDENTIALS = "SELECT url, token_enc FROM nodes WHERE id=:nid"

_SELECT_NODE_ID_BY_NAME = "SELECT id FROM nodes WHERE LOWER(name)=:nname"

_INSERT_NODE = (
    "INSERT INTO nodes (name, url, token_enc, capacity, enabled, created_at) "
    "VALUES (:name, :url, :token_enc, :capacity, :enabled, :created) "
    "RETURNING id INTO :new_id"
)

_UPDATE_NODE_CAPACITY = "UPDATE nodes SET capacity=:capacity WHERE id=:nid"

_UPDATE_NODE_URL = "UPDATE nodes SET url=:url WHERE id=:nid"

_UPDATE_NODE_ENABLED = "UPDATE nodes SET enabled=:enabled WHERE id=:nid"

_DELETE_NODE = "DELETE FROM nodes WHERE id=:nid"

_COUNT_SERVERS_ON_NODE = (
    "SELECT COUNT(*) FROM panel_servers s WHERE s.node_id IS NOT NULL AND " + _SERVER_NODE_ID + "=:nid"
)

# Exclude servers with no explicit node_id from capacity counts:
# such rows are unplaced/orphaned and should not block any node.
# (The _SERVER_NODE_ID NVL fallback remains for display queries only;
# _COUNT_SERVERS_ON_NODE and _SELECT_NODE_WITH_FREE_CAPACITY now filter
# with s.node_id IS NOT NULL to avoid counting unplaced servers.)
#
# LEFT JOIN on the owner rather than an inner one. panel_servers.user_id has a
# CASCADE constraint so an ownerless row should not exist, but an inner join
# would answer that impossibility by hiding the container — and a container
# nobody can see is still consuming that node's memory.
_SELECT_SERVERS_ON_NODE = (
    "SELECT s.id, s.name, s.runtime, s.version, s.memory_mb, s.cpu_percent, "
    "s.desired_state, s.created_at, s.user_id, s.node_id, u.username "
    "FROM panel_servers s LEFT JOIN panel_users u ON u.id = s.user_id "
    "WHERE " + _SERVER_NODE_ID + "=:nid "
    "ORDER BY s.created_at DESC, s.id "
    "FETCH FIRST :lim ROWS ONLY"
)

_COUNT_NODES = "SELECT COUNT(*) FROM nodes"

_SELECT_NODE_WITH_FREE_CAPACITY = (
    "SELECT n.id FROM nodes n WHERE n.enabled=1 AND n.capacity>0 AND "
    "(SELECT COUNT(*) FROM panel_servers s WHERE s.node_id IS NOT NULL AND "
    + _SERVER_NODE_ID + "=n.id) < n.capacity "
    "ORDER BY n.id FETCH FIRST 1 ROWS ONLY"
)

_NODES_TABLE = "NODES"

_OWNED_TABLES = (_NODES_TABLE,)

_MODEL_COLUMNS = {
    _NODES_TABLE: (
        "ID",
        "NAME",
        "URL",
        "TOKEN_ENC",
        "CAPACITY",
        "ENABLED",
        "CREATED_AT",
    ),
}

_ADDITIVE_COLUMNS = {
    _NODES_TABLE: {
        "NAME": "VARCHAR2(100 CHAR) NULL",
        "URL": "VARCHAR2(255 CHAR) NULL",
        "TOKEN_ENC": "VARCHAR2(2000 CHAR) NULL",
        "CAPACITY": "NUMBER DEFAULT 0 NOT NULL",
        "ENABLED": "NUMBER DEFAULT 1 NOT NULL",
    },
}

_CREATE_DDL = {
    _NODES_TABLE: (
        (
            "CREATE TABLE nodes ("
            "id NUMBER GENERATED BY DEFAULT AS IDENTITY, "
            "name VARCHAR2(100 CHAR) NOT NULL, "
            "url VARCHAR2(255 CHAR) NOT NULL, "
            "token_enc VARCHAR2(2000 CHAR) NOT NULL, "
            "capacity NUMBER DEFAULT 0 NOT NULL, "
            "enabled NUMBER DEFAULT 1 NOT NULL, "
            "created_at DATE NOT NULL, "
            "PRIMARY KEY (id))",
            "created nodes",
        ),
        (
            "CREATE UNIQUE INDEX ix_nodes_name_lower ON nodes (LOWER(name))",
            "created ix_nodes_name_lower",
        ),
    ),
}

_SELECT_NODE_TABLES = "SELECT table_name FROM user_tables"

_SELECT_NODE_TABLE_COLUMNS = (
    "SELECT column_name FROM user_tab_columns WHERE table_name = :t"
)

_ALREADY_THERE = ("ORA-00955", "ORA-01430")

_LOCKED = ("ORA-00054", "ORA-04021", "ORA-04020")

_DDL_TRIES = 8

_MISSING_COLUMN = "ORA-00904"

_MISSING_TABLE = "ORA-00942"

_NODE_SCHEMA_ENSURED = False
_NODE_SCHEMA_LOCK = threading.Lock()


class NodeCredentialError(Exception):
    pass


class NodeCapacityError(Exception):
    pass


class PanelSchemaMissing(Exception):
    """panel_servers or panel_users is not in this database.

    Raised instead of returning an empty list, because the two states read
    identically to an operator and mean opposite things: "this node holds no
    containers" is normal, "the hosting tables were never created here" means
    the answer on screen is not about this node at all. list_nodes_with_usage
    below degrades to servers=0 for the same missing table — it has to, since a
    node list that fails outright would hide the registry too — so this is the
    call that gets to say why the count was zero.
    """


def _clip_text(value, max_chars):
    text = str(value)
    if any("\ud800" <= ch <= "\udfff" for ch in text):
        text = text.encode("utf-8", "surrogatepass").decode("utf-8", "replace")
    text = text[:max_chars]
    encoded = text.encode("utf-8")
    if len(encoded) <= max_chars:
        return text
    return encoded[:max_chars].decode("utf-8", "ignore")


def _utc_now() -> datetime:
    return datetime.now(timezone.utc).replace(tzinfo=None)


def _iso(value) -> str:
    if value is None:
        return ""
    if isinstance(value, datetime):
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value.isoformat()
    return str(value)


def _node_key(node_id):
    if node_id is None or isinstance(node_id, bool):
        return None
    try:
        key = int(node_id)
    except (TypeError, ValueError):
        return None
    if key < 1 or len(str(key)) > NODE_ID_MAX_DIGITS:
        return None
    return key


def _valid_name(name) -> str:
    text = (name or "").strip()
    if len(text) < NAME_MIN_CHARS or len(text) > NAME_INPUT_MAX_CHARS:
        raise ValueError(
            f"the node name must be between {NAME_MIN_CHARS} and "
            f"{NAME_INPUT_MAX_CHARS} characters"
        )
    if any("\ud800" <= ch <= "\udfff" for ch in text):
        raise ValueError(
            "the node name must not contain unpaired surrogate characters"
        )
    return _clip_text(text, NAME_MAX_CHARS)


def _valid_origin(origin, prefix) -> str:
    parts = urlsplit(origin)
    if parts.scheme not in _URL_SCHEMES:
        raise ValueError(prefix + "the node URL must start with http:// or https://")
    if not parts.netloc or not parts.hostname:
        raise ValueError(prefix + "the node URL must include a host")
    if "@" in parts.netloc:
        raise ValueError(prefix + "the node URL must not embed credentials")
    if parts.path not in ("", "/"):
        raise ValueError(prefix + "the node URL must be a bare origin, with no path")
    if parts.query or parts.fragment:
        raise ValueError(
            prefix
            + "the node URL must be a bare origin, with no query and no fragment"
        )
    try:
        port = parts.port
    except ValueError as exc:
        raise ValueError(prefix + "the node URL has an unusable port") from exc
    if port is not None and not 1 <= port <= 65535:
        raise ValueError(prefix + "the node URL has an unusable port")
    return parts.scheme + "://" + parts.netloc.lower()


def _valid_url(url) -> str:
    text = (url or "").strip()
    if not text:
        raise ValueError("a node requires a base URL")
    if any("\ud800" <= ch <= "\udfff" for ch in text):
        raise ValueError(
            "the node URL must not contain unpaired surrogate characters"
        )
    candidates = [item.strip() for item in text.split(",") if item.strip()]
    if not candidates:
        raise ValueError("a node requires a base URL")
    if len(candidates) > URL_MAX_ORIGINS:
        raise ValueError(
            f"a node URL holds at most {URL_MAX_ORIGINS} comma-separated origins"
        )
    origins = []
    for candidate in candidates:
        # Name the offending origin only when there is more than one, so a
        # single-URL node keeps the message it has always produced.
        prefix = f"{candidate}: " if len(candidates) > 1 else ""
        origin = _valid_origin(candidate, prefix)
        if origin not in origins:
            origins.append(origin)
    joined = ",".join(origins)
    if len(joined) > URL_MAX_CHARS:
        raise ValueError(f"the node URL must be at most {URL_MAX_CHARS} characters")
    return joined


def _origin_travels_cleartext(origin) -> bool:
    parts = urlsplit(origin)
    if parts.scheme != "http":
        return False
    host = parts.hostname or ""
    if host in _LOOPBACK_HOST_NAMES:
        return False
    try:
        if ipaddress.ip_address(host).is_loopback:
            return False
    except ValueError:
        pass
    return True


def _warn_if_token_travels_cleartext(node_url) -> None:
    for origin in str(node_url or "").split(","):
        origin = origin.strip()
        if not origin or not _origin_travels_cleartext(origin):
            continue
        _debug_print(
            f"[node_registry] WARNING: node URL {origin} is plain http:// to a "
            f"host that is not loopback. Every control call to this node sends its "
            f"agent token in an Authorization: Bearer header, so the token crosses "
            f"the network unencrypted, and that token grants full control of this "
            f"host's container daemon. Use https:// unless the node is reachable "
            f"only over loopback.",
            file=stderr,
        )


def _valid_capacity(capacity) -> int:
    if isinstance(capacity, bool):
        raise ValueError("the node capacity must be a whole number")
    try:
        value = int(capacity)
    except (TypeError, ValueError) as exc:
        raise ValueError("the node capacity must be a whole number") from exc
    if value < 0 or value > CAPACITY_MAX:
        raise ValueError(f"the node capacity must be between 0 and {CAPACITY_MAX}")
    return value


def _valid_token(token) -> str:
    text = (token or "").strip()
    if not text:
        raise ValueError("a node requires an agent token")
    limit = TOKEN_ENC_MAX_CHARS if looks_encrypted(text) else TOKEN_MAX_CHARS
    if len(text) > limit:
        raise ValueError(f"the node token must be at most {limit} characters")
    return text


def _seal_token(token) -> str:
    text = _valid_token(token)
    sealed = text if looks_encrypted(text) else encrypt(text)
    if len(sealed) > TOKEN_ENC_MAX_CHARS:
        raise ValueError(
            "the encrypted node token is longer than the token_enc column holds"
        )
    return sealed


def _unseal_token(value, node_id) -> str:
    text = "" if value is None else str(value).strip()
    if not text:
        raise NodeCredentialError(f"node {node_id} has no stored agent token")
    if not looks_encrypted(text):
        return text
    try:
        plain = decrypt_strict(text)
    except Exception as exc:
        raise NodeCredentialError(
            f"the stored agent token for node {node_id} is ciphertext this "
            f"process cannot read: it holds key {key_fingerprint()} and the "
            f"value was written under another one (see ENCRYPTION_KEYS_OLD / "
            f"rekey_encrypted.py)"
        ) from exc
    if not plain:
        raise NodeCredentialError(
            f"the stored agent token for node {node_id} decrypts to an empty "
            f"string, which is not a usable bearer token"
        )
    return plain


def _is_integrity_error(exc) -> bool:
    try:
        import oracledb
    except ImportError:
        oracledb = None
    if oracledb is not None and isinstance(exc, oracledb.IntegrityError):
        return True
    message = str(exc)
    return any(tag in message for tag in _INTEGRITY_ORA_CODES)


def _node_conn():
    try:
        return database._oracle_conn()
    except Exception as exc:
        if not database._is_pool_exhausted(exc):
            raise
        database._note_pool_busy()
        raise database.OraclePoolExhausted(f"Oracle unavailable: {exc}") from exc


def _node_dict(row):
    if row is None:
        return None
    return {
        "id": int(row["id"]),
        "name": row["name"],
        "url": row["url"],
        "capacity": int(row["capacity"] or 0),
        "enabled": int(row["enabled"] or 0),
        "created_at": _iso(row["created_at"]),
    }


def _fetch_one_dict(cur):
    return database._oracle_dict_row(cur, cur.fetchone())


def _node_usage_dict(row):
    node = _node_dict(row)
    if node is None:
        return None
    servers = int(row["servers"] or 0)
    node["servers"] = servers
    node["free"] = max(0, node["capacity"] - servers)
    return node


def _int_or_none(value):
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _server_on_node_dict(row):
    """One panel_servers row as the console's node view needs it.

    `placed` distinguishes a server the placer actually wrote this node onto
    from one that is only counted here because node_id is NULL and this is the
    lowest-numbered node. They behave differently the moment a second node is
    registered — an unplaced row keeps following whichever node has the lowest
    id — so the page has to be able to tell them apart.

    No password_hash, no token, nothing from the owner but the id and the
    username: this payload crosses two hops to reach a browser.
    """
    if row is None:
        return None
    return {
        "id": str(row["id"] or ""),
        "name": row["name"],
        "runtime": row["runtime"],
        "version": row["version"],
        "memory_mb": _int_or_none(row["memory_mb"]),
        "cpu_percent": _int_or_none(row["cpu_percent"]),
        "desired_state": row["desired_state"],
        "created_at": _iso(row["created_at"]),
        "user_id": str(row["user_id"] or ""),
        "username": row["username"],
        "placed": row["node_id"] is not None,
    }


def _fetch_all_dicts(cur):
    rows = cur.fetchall()
    return [database._oracle_dict_row(cur, row) for row in rows]


def _fetch_count(cur) -> int:
    row = cur.fetchone()
    if row is None:
        return 0
    return int(row[0] or 0)


def _servers_on_node(cur, key) -> int:
    try:
        cur.execute(_COUNT_SERVERS_ON_NODE, {"nid": key})
    except Exception as exc:
        message = str(exc)
        if _MISSING_TABLE not in message and _MISSING_COLUMN not in message:
            raise
        return 0
    return _fetch_count(cur)


def _returned_id(holder) -> int:
    value = holder.getvalue()
    if isinstance(value, (list, tuple)):
        value = value[0] if value else None
    if value is None:
        raise RuntimeError("the database did not report the new node id")
    return int(value)


def _node_ddl(cur, sql, describe):
    for _ in range(_DDL_TRIES):
        try:
            cur.execute(sql)
            _debug_print(f"[node_registry] schema: {describe}")
            return
        except Exception as exc:
            msg = str(exc)
            if any(tag in msg for tag in _ALREADY_THERE):
                return
            if not any(tag in msg for tag in _LOCKED):
                raise
            time.sleep(1.0)
    raise RuntimeError(
        f"could not lock the table to {describe} after {_DDL_TRIES} tries"
    )


def _node_schema_pass():
    conn = _node_conn()
    try:
        cur = conn.cursor()
        cur.execute(_SELECT_NODE_TABLES)
        present = {row[0].upper() for row in cur.fetchall()} & set(_OWNED_TABLES)
        missing = [table for table in _OWNED_TABLES if table not in present]
        if missing:
            _debug_print(
                "[node_registry] schema: creating "
                + ", ".join(table.lower() for table in missing)
            )
            for table in missing:
                for sql, describe in _CREATE_DDL[table]:
                    _node_ddl(cur, sql, describe)
        for table in _OWNED_TABLES:
            if table not in present:
                continue
            cur.execute(_SELECT_NODE_TABLE_COLUMNS, {"t": table})
            have = {row[0].upper() for row in cur.fetchall()}
            known = _ADDITIVE_COLUMNS.get(table, {})
            for column in _MODEL_COLUMNS[table]:
                if column in have:
                    continue
                column_type = known.get(column)
                if not column_type:
                    _debug_print(
                        f"[node_registry] WARNING: {table.lower()}.{column.lower()} "
                        f"is in the model but not in the database, and "
                        f"_ADDITIVE_COLUMNS in node_registry.py has no DDL for it. "
                        f"Every query selecting it will fail with "
                        f"{_MISSING_COLUMN} until the column is added.",
                        file=stderr,
                    )
                    continue
                if not _IDENTIFIER_RE.fullmatch(table) or not _IDENTIFIER_RE.fullmatch(column):
                    raise ValueError(f"invalid SQL identifier in DDL: {table!r}.{column!r}")
                _node_ddl(
                    cur,
                    f"ALTER TABLE {table} ADD ({column} {column_type})",
                    f"added {table.lower()}.{column.lower()}",
                )
    finally:
        conn.close()


def ensure_node_schema(*, _force=False) -> None:
    global _NODE_SCHEMA_ENSURED
    if _NODE_SCHEMA_ENSURED and not _force:
        return
    with _NODE_SCHEMA_LOCK:
        if _NODE_SCHEMA_ENSURED and not _force:
            return
        _node_schema_pass()
        _NODE_SCHEMA_ENSURED = True


def _with_conn(work):
    conn = _node_conn()
    try:
        return work(conn)
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        raise
    finally:
        conn.close()


def _run_with_heal(work):
    try:
        return _with_conn(work)
    except Exception as exc:
        if _MISSING_COLUMN not in str(exc):
            raise
        ensure_node_schema(_force=True)
        return _with_conn(work)


def _run_on_conn_with_heal(conn, work):
    try:
        return work(conn)
    except Exception as exc:
        if _MISSING_COLUMN not in str(exc):
            raise
        try:
            conn.rollback()
        except Exception:
            pass
        ensure_node_schema(_force=True)
        return work(conn)


def create_node(*, name, url, token, capacity):
    node_name = _valid_name(name)
    node_url = _valid_url(url)
    node_capacity = _valid_capacity(capacity)
    sealed = _seal_token(token)

    def _insert(conn):
        cur = conn.cursor()
        cur.execute(_SELECT_NODE_ID_BY_NAME, {"nname": node_name.lower()})
        if cur.fetchone() is not None:
            raise ValueError("a node with that name already exists")
        holder = cur.var(int)
        try:
            cur.execute(
                _INSERT_NODE,
                {
                    "name": node_name,
                    "url": node_url,
                    "token_enc": sealed,
                    "capacity": node_capacity,
                    "enabled": 1,
                    "created": _utc_now(),
                    "new_id": holder,
                },
            )
            conn.commit()
        except Exception as exc:
            conn.rollback()
            if not _is_integrity_error(exc):
                raise
            if _UNIQUE_ORA_CODE in str(exc):
                raise ValueError("a node with that name already exists") from exc
            raise ValueError(f"the database rejected the node row: {exc}") from exc
        return _returned_id(holder)

    node_id = _run_with_heal(_insert)
    _warn_if_token_travels_cleartext(node_url)
    return node_id


def list_nodes():
    def _query(conn):
        cur = conn.cursor()
        cur.execute(_SELECT_NODES, {"lim": NODE_LIST_MAX})
        return [_node_dict(row) for row in _fetch_all_dicts(cur)]

    return _run_with_heal(_query)


def list_nodes_with_usage():
    def _query(conn):
        cur = conn.cursor()
        cur.execute(_SELECT_NODES_WITH_USAGE, {"lim": NODE_LIST_MAX})
        return [_node_usage_dict(row) for row in _fetch_all_dicts(cur)]

    try:
        return _run_with_heal(_query)
    except Exception as exc:
        message = str(exc)
        if _MISSING_TABLE not in message and _MISSING_COLUMN not in message:
            raise
    nodes = list_nodes()
    for node in nodes:
        node["servers"] = 0
        node["free"] = node["capacity"]
    return nodes


def list_servers_on_node(node_id, limit=SERVER_LIST_MAX):
    """The containers this node holds, each with the panel user who owns it.

    list_nodes_with_usage returns a count; this returns the rows behind it, by
    the same NVL rule, so the two cannot disagree. Ordered newest first because
    the row an operator is looking for after a provisioning failure is the one
    that was just created.

    Raises PanelSchemaMissing when the hosting tables are absent, so "zero
    containers" and "no hosting schema on this database" stay distinguishable.
    """
    key = _node_key(node_id)
    if key is None:
        return []
    try:
        cap = int(limit)
    except (TypeError, ValueError):
        cap = SERVER_LIST_MAX
    cap = max(1, min(cap, SERVER_LIST_MAX))

    def _query(conn):
        cur = conn.cursor()
        cur.execute(_SELECT_SERVERS_ON_NODE, {"nid": key, "lim": cap})
        return [_server_on_node_dict(row) for row in _fetch_all_dicts(cur)]

    try:
        return _run_with_heal(_query)
    except Exception as exc:
        message = str(exc)
        if _MISSING_TABLE in message or _MISSING_COLUMN in message:
            raise PanelSchemaMissing(
                "The hosting tables (panel_servers / panel_users) are missing "
                "or out of date on this database, so the containers on this "
                "node cannot be listed. Start the panel once — it creates and "
                "upgrades its own schema.") from exc
        raise


def get_node_credentials(node_id):
    key = _node_key(node_id)
    if key is None:
        return None

    def _query(conn):
        cur = conn.cursor()
        cur.execute(_SELECT_NODE_CREDENTIALS, {"nid": key})
        return _fetch_one_dict(cur)

    row = _run_with_heal(_query)
    if row is None:
        return None
    return {"url": row["url"], "token": _unseal_token(row["token_enc"], key)}


def update_node_capacity(node_id, capacity):
    key = _node_key(node_id)
    if key is None:
        return False
    node_capacity = _valid_capacity(capacity)

    def _do_update(conn):
        cur = conn.cursor()
        cur.execute(_UPDATE_NODE_CAPACITY, {"capacity": node_capacity, "nid": key})
        conn.commit()
        return (cur.rowcount or 0) == 1

    return _run_with_heal(_do_update)


def update_node_url(node_id, url):
    key = _node_key(node_id)
    if key is None:
        return False
    node_url = _valid_url(url)

    def _do_update(conn):
        cur = conn.cursor()
        cur.execute(_UPDATE_NODE_URL, {"url": node_url, "nid": key})
        conn.commit()
        return (cur.rowcount or 0) == 1

    return _run_with_heal(_do_update)


def set_node_enabled(node_id, enabled):
    key = _node_key(node_id)
    if key is None:
        return False

    def _do_update(conn):
        cur = conn.cursor()
        cur.execute(
            _UPDATE_NODE_ENABLED,
            {"enabled": 1 if enabled else 0, "nid": key},
        )
        conn.commit()
        return (cur.rowcount or 0) == 1

    return _run_with_heal(_do_update)


def delete_node(node_id):
    key = _node_key(node_id)
    if key is None:
        return False

    def _do_delete(conn):
        cur = conn.cursor()
        if _servers_on_node(cur, key) > 0:
            raise ValueError(
                "this node still hosts servers, and existing servers are never "
                "migrated; set its capacity to 0 to stop new placements instead "
                "of deleting it"
            )
        cur.execute(_DELETE_NODE, {"nid": key})
        conn.commit()
        return (cur.rowcount or 0) == 1

    return _run_with_heal(_do_delete)


def get_server(server_id):
    """Get a single panel_servers row by server_id."""
    sid = str(server_id or "").strip()
    if not sid:
        return None

    def _query(conn):
        cur = conn.cursor()
        cur.execute(
            "SELECT s.id, s.name, s.user_id, s.node_id "
            "FROM panel_servers s WHERE s.id = :sid",
            {"sid": sid}
        )
        return _fetch_one_dict(cur)

    try:
        return _run_with_heal(_query)
    except Exception as exc:
        _debug_print(f"[node_registry] get_server failed for {sid}: {exc}")
        return None


def delete_server(server_id):
    """Delete a single panel_servers row by server_id."""
    sid = str(server_id or "").strip()
    if not sid:
        return False

    def _do_delete(conn):
        cur = conn.cursor()
        cur.execute("DELETE FROM panel_servers WHERE id = :sid", {"sid": sid})
        conn.commit()
        return (cur.rowcount or 0) == 1

    try:
        return _run_with_heal(_do_delete)
    except Exception as exc:
        _debug_print(f"[node_registry] delete_server failed for {sid}: {exc}")
        return False


def placement_capacity_available() -> bool:
    def _probe(conn):
        cur = conn.cursor()
        cur.execute(_COUNT_NODES)
        if _fetch_count(cur) < 1:
            return True
        cur.execute(_SELECT_NODE_WITH_FREE_CAPACITY)
        return cur.fetchone() is not None

    try:
        return _with_conn(_probe)
    except Exception as exc:
        message = str(exc)
        if _MISSING_TABLE not in message and _MISSING_COLUMN not in message:
            raise
        return True


def pick_node_for_new_server(conn=None):
    def _query(placement_conn):
        cur = placement_conn.cursor()
        cur.execute(_SELECT_NODE_WITH_FREE_CAPACITY)
        row = cur.fetchone()
        if row is not None:
            return int(row[0])
        cur.execute(_COUNT_NODES)
        if _fetch_count(cur) > 0:
            raise NodeCapacityError(
                "every configured node is full or disabled, so there is no room "
                "for a new server right now; raise a node's capacity or add "
                "another node"
            )
        return None

    try:
        if conn is None:
            return _run_with_heal(_query)
        return _run_on_conn_with_heal(conn, _query)
    except NodeCapacityError:
        raise
    except Exception as exc:
        message = str(exc)
        if _MISSING_TABLE not in message and _MISSING_COLUMN not in message:
            raise
        return None
